apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dev
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis
            - name: DB_HOST
              value: db
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"